export type ProgramType = "Fellowship" | "Accelerator" | "Incubator" | "Grant";

export type ProgramStatus = "Open" | "Closing Soon" | "Closed" | "Rolling";

export type Program = {
  id: string;
  name: string;
  org: string;
  type: ProgramType;
  region: string;
  focus: string;
  equity: string;
  stipend: string;
  duration: string;
  location: string;
  deadline: string;
  status: ProgramStatus;
  description: string;
  eligibility: string[];
  perks: { title: string; detail: string }[];
  featured: boolean;
  icon: string;
  stickyColor: "#FEF9C3" | "#DCFCE7" | "#FCE7F3" | "#DBEAFE" | "#FFEDD5" | "#EDE9FE";
};

export const programs: Program[] = [

  {
    id: "y-combinator-s26",
    name: "YC Summer 2026",
    org: "Y Combinator",
    type: "Accelerator",
    region: "North America",
    focus: "General",
    equity: "7%",
    stipend: "$500,000",
    duration: "12 weeks",
    location: "San Francisco / Hybrid",
    deadline: "May 22, 2026",
    status: "Open",
    description:
      "YC helps early teams iterate fast, find product-market fit, and raise with confidence. Founders get weekly group office hours, tactical partner support, and a global alumni network. Demo Day remains one of the highest-signal investor events in the ecosystem.",
    eligibility: [
      "At least one full-time technical or domain-expert founder",
      "Working product prototype or active pilot customers",
      "Team availability for full program participation",
    ],
    perks: [
      { title: "Capital", detail: "$500k standard YC deal" },
      { title: "Mentorship", detail: "Weekly partner group office hours" },
      { title: "Network", detail: "Access to 9,000+ YC alumni founders" },
      { title: "Fundraising", detail: "Demo Day and investor prep support" },
    ],
    featured: true,
    icon: "rocket_launch",
    stickyColor: "#FEF9C3",
  },
  {
    id: "techstars-anywhere-2026",
    name: "Techstars Anywhere",
    org: "Techstars",
    type: "Accelerator",
    region: "Global",
    focus: "General",
    equity: "6%",
    stipend: "$120,000",
    duration: "13 weeks",
    location: "Remote",
    deadline: "Jun 10, 2026",
    status: "Open",
    description:
      "Techstars Anywhere supports globally distributed teams with structured mentorship and investor introductions. The cohort model is intense and operator-led, with accountability each week. Founders gain a practical playbook for growth, hiring, and fundraising.",
    eligibility: [
      "Pre-seed or seed-stage startups",
      "Two or more committed founders preferred",
      "Comfort with a remote-first program cadence",
    ],
    perks: [
      { title: "Mentor Network", detail: "1,000+ mentors across sectors" },
      { title: "Global Community", detail: "Alumni in 150+ countries" },
      { title: "Investor Access", detail: "Warm intros to active seed funds" },
      { title: "Perks", detail: "$2M+ in cloud and tooling credits" },
    ],
    featured: true,
    icon: "public",
    stickyColor: "#DBEAFE",
  },
  {
    id: "antler-berlin-residency",
    name: "Founder Residency Berlin",
    org: "Antler",
    type: "Incubator",
    region: "Europe",
    focus: "General",
    equity: "10%",
    stipend: "None",
    duration: "10 weeks",
    location: "Berlin / In-Person",
    deadline: "Jun 15, 2026",
    status: "Open",
    description:
      "Antler helps founders form teams, validate ideas, and launch venture-scale startups from scratch. The residency is designed for speed and experimentation with close coaching. Teams that meet investment criteria can secure immediate pre-seed backing.",
    eligibility: [
      "Founders open to forming teams during the program",
      "Experience in product, engineering, or domain operations",
      "Availability in Berlin throughout residency",
    ],
    perks: [
      { title: "Co-founder Matching", detail: "Structured team formation support" },
      { title: "Investment", detail: "Pre-seed checks for top teams" },
      { title: "Workshops", detail: "Validation and GTM sprints" },
      { title: "Community", detail: "Strong operator and founder network" },
    ],
    featured: false,
    icon: "groups",
    stickyColor: "#EDE9FE",
  },
  {
    id: "eu-eic-accelerator",
    name: "EIC Accelerator",
    org: "European Innovation Council",
    type: "Grant",
    region: "Europe",
    focus: "Deep Tech",
    equity: "Equity-free",
    stipend: "€2,500,000",
    duration: "9-12 months",
    location: "EU / Hybrid",
    deadline: "Sep 18, 2026",
    status: "Open",
    description:
      "EIC Accelerator funds high-risk deep-tech innovation with non-dilutive grants and optional blended finance. The program is highly competitive and evidence-driven. Winning teams gain credibility, procurement access, and strategic EU visibility.",
    eligibility: [
      "EU or associated-country startup/SME",
      "TRL advancement potential with strong technical novelty",
      "Clear commercialization and scaling plan",
    ],
    perks: [
      { title: "Grant", detail: "Up to €2.5M equity-free" },
      { title: "Advisory", detail: "Business acceleration services" },
      { title: "Credibility", detail: "EU-recognized innovation validation" },
      { title: "Follow-on", detail: "Optional blended finance pathways" },
    ],
    featured: true,
    icon: "science",
    stickyColor: "#DCFCE7",
  },
  {
    id: "foundersfactory-africa",
    name: "Venture Scale for Africa",
    org: "Founders Factory Africa",
    type: "Accelerator",
    region: "Africa",
    focus: "Fintech",
    equity: "5%",
    stipend: "$60,000",
    duration: "6 months",
    location: "Johannesburg / Hybrid",
    deadline: "Jul 31, 2026",
    status: "Open",
    description:
      "This program supports fintech founders building financial access and infrastructure across African markets. Teams receive practical growth support, distribution partnerships, and investor readiness training. The curriculum emphasizes regulatory navigation and responsible scaling.",
    eligibility: [
      "African-focused product and market strategy",
      "Demonstrable traction with users or revenue",
      "Core team available for hybrid engagement",
    ],
    perks: [
      { title: "Funding", detail: "Initial capital plus follow-on pathways" },
      { title: "Partnerships", detail: "Corporate and payment ecosystem access" },
      { title: "Mentorship", detail: "Operator-led growth support" },
      { title: "Community", detail: "Pan-African founder network" },
    ],
    featured: false,
    icon: "payments",
    stickyColor: "#FFEDD5",
  },
  {
    id: "google-startups-accelerator-cloud",
    name: "Google for Startups Accelerator Cloud",
    org: "Google",
    type: "Accelerator",
    region: "Global",
    focus: "Deep Tech",
    equity: "Equity-free",
    stipend: "$100,000",
    duration: "10 weeks",
    location: "Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "Google's cloud accelerator supports startups scaling machine learning and data infrastructure. Founders receive architecture guidance from product and engineering experts. The program is designed to improve reliability, velocity, and cost efficiency at scale.",
    eligibility: [
      "Cloud-native product with measurable usage",
      "Engineering team able to execute technical milestones",
      "Commitment to program sessions and office hours",
    ],
    perks: [
      { title: "Cloud Credits", detail: "Significant GCP credits" },
      { title: "Experts", detail: "Dedicated support from Google engineers" },
      { title: "Go-to-Market", detail: "Co-marketing opportunities" },
      { title: "Peer Group", detail: "Global cohort of technical founders" },
    ],
    featured: true,
    icon: "cloud",
    stickyColor: "#DBEAFE",
  },
  {
    id: "village-capital-future-of-work",
    name: "Future of Work Africa",
    org: "Village Capital",
    type: "Fellowship",
    region: "Africa",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$25,000",
    duration: "14 weeks",
    location: "Nairobi / Hybrid",
    deadline: "Aug 20, 2026",
    status: "Open",
    description:
      "Village Capital runs founder-first fellowships focused on inclusive innovation and measurable impact. The peer-selected model helps teams sharpen value propositions and execution plans. Cohorts receive robust support around impact metrics and capital readiness.",
    eligibility: [
      "Impact-driven startup with clear beneficiary outcomes",
      "Operations in Africa with early traction",
      "Founders committed to peer-led sessions",
    ],
    perks: [
      { title: "Catalytic Capital", detail: "Equity-free grants for select teams" },
      { title: "Peer Network", detail: "Founder cohort with reciprocal review" },
      { title: "Impact Support", detail: "Measurement and storytelling tools" },
      { title: "Investor Readiness", detail: "Preparation for mission-aligned funds" },
    ],
    featured: false,
    icon: "volunteer_activism",
    stickyColor: "#FCE7F3",
  },
  {
    id: "seeds-for-climate-latam",
    name: "Seeds for Climate LATAM",
    org: "IDB Lab",
    type: "Grant",
    region: "LATAM",
    focus: "Climate",
    equity: "Equity-free",
    stipend: "$75,000",
    duration: "16 weeks",
    location: "Bogota / Hybrid",
    deadline: "Aug 5, 2026",
    status: "Closing Soon",
    description:
      "Seeds for Climate backs startups tackling adaptation, mitigation, and resilient infrastructure in Latin America. The initiative combines grant support with implementation partnerships. Teams also receive practical policy and procurement guidance for regional expansion.",
    eligibility: [
      "Startup operating in one or more LATAM countries",
      "Climate solution with measurable environmental impact",
      "Pilot readiness with local stakeholders",
    ],
    perks: [
      { title: "Grant Funding", detail: "Up to USD 75k non-dilutive" },
      { title: "Market Access", detail: "Introductions to regional partners" },
      { title: "Policy Navigation", detail: "Support for public-sector adoption" },
      { title: "Advisory", detail: "Mentorship from climate operators" },
    ],
    featured: true,
    icon: "eco",
    stickyColor: "#DCFCE7",
  },
  {
    id: "startup-chile-build",
    name: "Build Program",
    org: "Start-Up Chile",
    type: "Incubator",
    region: "LATAM",
    focus: "General",
    equity: "Equity-free",
    stipend: "$30,000",
    duration: "4 months",
    location: "Santiago / Hybrid",
    deadline: "Oct 1, 2026",
    status: "Open",
    description:
      "Start-Up Chile helps founders validate products and expand across Latin America through a structured incubation track. Teams benefit from local market insights and operational support. The program is known for its strong community and practical founder education.",
    eligibility: [
      "Early-stage startup with MVP",
      "International and local founders welcome",
      "Ability to participate in hybrid activities",
    ],
    perks: [
      { title: "Grant", detail: "USD 30k equity-free support" },
      { title: "Workspace", detail: "Access to local startup ecosystem hubs" },
      { title: "Mentors", detail: "Regional operator and investor guidance" },
      { title: "Visa Support", detail: "Founder relocation facilitation" },
    ],
    featured: false,
    icon: "travel_explore",
    stickyColor: "#FEF9C3",
  },
  {
    id: "entrepreneur-first-singapore",
    name: "EF Singapore Cohort",
    org: "Entrepreneur First",
    type: "Incubator",
    region: "Asia",
    focus: "Deep Tech",
    equity: "10%",
    stipend: "$20,000",
    duration: "14 weeks",
    location: "Singapore / In-Person",
    deadline: "Jul 10, 2026",
    status: "Closing Soon",
    description:
      "Entrepreneur First invests in individuals before a company is formed, then helps teams build deep-tech ventures quickly. The program prioritizes technical talent and founder matching. Selected teams receive pre-seed capital and an intense build environment.",
    eligibility: [
      "Strong technical or research background",
      "Willingness to form or join a founding team",
      "Availability for full in-person cohort",
    ],
    perks: [
      { title: "Pre-seed Capital", detail: "Initial investment for selected teams" },
      { title: "Talent Network", detail: "Top-tier technical founder pool" },
      { title: "Coaching", detail: "Weekly venture design support" },
      { title: "Investor Access", detail: "Global follow-on fundraising support" },
    ],
    featured: true,
    icon: "bolt",
    stickyColor: "#EDE9FE",
  },
  {
    id: "founders-bootcamp-africa",
    name: "Impact Founder Fellowship",
    org: "ALX Ventures",
    type: "Fellowship",
    region: "Africa",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$10,000",
    duration: "8 weeks",
    location: "Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "This fellowship supports emerging founders solving access gaps in health, education, and jobs. The curriculum blends practical execution with storytelling and fundraising preparation. Alumni continue receiving mentorship through a regional operator network.",
    eligibility: [
      "Founder-led startup with impact mission",
      "Product already serving users",
      "Ability to attend weekly remote sessions",
    ],
    perks: [
      { title: "Mini-Grants", detail: "Catalytic stipends for growth experiments" },
      { title: "Training", detail: "Execution, GTM, and leadership workshops" },
      { title: "Mentors", detail: "Sector operators and investors" },
      { title: "Alumni Community", detail: "Long-term peer support network" },
    ],
    featured: false,
    icon: "school",
    stickyColor: "#FCE7F3",
  },
  {
    id: "antai-incubator-asia",
    name: "Asia Future Commerce Incubator",
    org: "Antai Global",
    type: "Incubator",
    region: "Asia",
    focus: "Fintech",
    equity: "5%",
    stipend: "$40,000",
    duration: "20 weeks",
    location: "Shanghai / Hybrid",
    deadline: "Nov 12, 2026",
    status: "Open",
    description:
      "This incubator helps early commerce and fintech ventures validate unit economics in large, fast-moving markets. Teams work closely with operators on localization and regulatory execution. The program includes milestones tied to customer and revenue outcomes.",
    eligibility: [
      "Seed-stage startup in fintech or commerce infrastructure",
      "Clear strategy for Asian market entry or growth",
      "Ability to attend hybrid review sessions",
    ],
    perks: [
      { title: "Partner Access", detail: "Corporate channel introductions" },
      { title: "Advisory", detail: "Regulatory and market-entry guidance" },
      { title: "Funding", detail: "Convertible note for top performers" },
      { title: "Workspace", detail: "Incubator offices and demo venues" },
    ],
    featured: false,
    icon: "storefront",
    stickyColor: "#FFEDD5",
  },
  {
    id: "schmidt-futures-fellows",
    name: "Schmidt Futures Venture Fellows",
    org: "Schmidt Futures",
    type: "Fellowship",
    region: "Global",
    focus: "Deep Tech",
    equity: "Equity-free",
    stipend: "$50,000",
    duration: "6 months",
    location: "Remote",
    deadline: "Sep 5, 2026",
    status: "Open",
    description:
      "The fellowship backs technical founders applying frontier science to pressing global problems. Fellows receive strategic coaching and connections to mission-aligned capital. The program strongly emphasizes technical rigor and social value.",
    eligibility: [
      "Scientist or technical founder with venture intent",
      "Compelling thesis for real-world deployment",
      "Commitment to measurable milestones",
    ],
    perks: [
      { title: "Non-dilutive Capital", detail: "USD 50k fellow support" },
      { title: "Advisors", detail: "Expert network across policy and science" },
      { title: "Visibility", detail: "Showcase opportunities with partners" },
      { title: "Community", detail: "Global peer cohort" },
    ],
    featured: true,
    icon: "biotech",
    stickyColor: "#DBEAFE",
  },
  {
    id: "founders-live-europe",
    name: "Founders Live Europe Catalyst",
    org: "Founders Live",
    type: "Accelerator",
    region: "Europe",
    focus: "General",
    equity: "Equity-free",
    stipend: "None",
    duration: "10 weeks",
    location: "Remote / Europe",
    deadline: "Aug 30, 2026",
    status: "Open",
    description:
      "Founders Live Catalyst supports startup teams preparing for market launch and early fundraising. The model combines live feedback, operator mentoring, and weekly pitch iteration. It works well for teams seeking momentum before a larger raise.",
    eligibility: [
      "Early-stage startup with validated problem",
      "Europe-based or Europe-focused team",
      "Willingness to present weekly progress",
    ],
    perks: [
      { title: "Pitch Practice", detail: "Structured weekly presentation rounds" },
      { title: "Mentorship", detail: "Hands-on guidance from founders" },
      { title: "Community", detail: "Regional startup ecosystem access" },
      { title: "Exposure", detail: "Demo opportunities with investors" },
    ],
    featured: false,
    icon: "forum",
    stickyColor: "#FEF9C3",
  },
  {
    id: "masschallenge-healthtech",
    name: "MassChallenge HealthTech",
    org: "MassChallenge",
    type: "Accelerator",
    region: "North America",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$15,000",
    duration: "4 months",
    location: "Boston / Hybrid",
    deadline: "Jun 30, 2026",
    status: "Closing Soon",
    description:
      "MassChallenge HealthTech supports founders modernizing care delivery, diagnostics, and patient experience. The program is partner-driven and focused on real pilots with hospitals and payers. Founders benefit from high-quality mentorship without equity requirements.",
    eligibility: [
      "Healthtech startup with MVP and pilot readiness",
      "Ability to engage with healthcare partners",
      "Commitment to compliance and evidence standards",
    ],
    perks: [
      { title: "Non-dilutive Awards", detail: "Cash prizes for top teams" },
      { title: "Pilot Pathways", detail: "Introductions to healthcare systems" },
      { title: "Mentorship", detail: "Sector experts and operators" },
      { title: "Visibility", detail: "Demo exposure to industry stakeholders" },
    ],
    featured: false,
    icon: "health_and_safety",
    stickyColor: "#DCFCE7",
  },
  {
    id: "norrsken-impact-accelerator",
    name: "Norrsken Impact Accelerator",
    org: "Norrsken",
    type: "Accelerator",
    region: "Europe",
    focus: "Climate",
    equity: "6%",
    stipend: "€120,000",
    duration: "12 weeks",
    location: "Stockholm / Hybrid",
    deadline: "Jul 14, 2026",
    status: "Closing Soon",
    description:
      "Norrsken accelerates startups solving climate and societal challenges with scalable business models. The program combines investor access with practical support on growth and impact measurement. Alumni benefit from deep ties to the European impact capital ecosystem.",
    eligibility: [
      "Seed-stage impact startup with traction",
      "Clear climate or social outcomes",
      "Team availability for hybrid sprint cycles",
    ],
    perks: [
      { title: "Capital", detail: "Investment plus investor introductions" },
      { title: "Impact Support", detail: "Frameworks for measurement and reporting" },
      { title: "Mentorship", detail: "Operator-led tactical sessions" },
      { title: "Community", detail: "Access to Norrsken ecosystem" },
    ],
    featured: true,
    icon: "forest",
    stickyColor: "#DCFCE7",
  },
  {
    id: "startupbootcamp-fintech-apac",
    name: "FinTech APAC Scale Program",
    org: "Startupbootcamp",
    type: "Accelerator",
    region: "Asia",
    focus: "Fintech",
    equity: "6%",
    stipend: "$45,000",
    duration: "13 weeks",
    location: "Singapore / Hybrid",
    deadline: "Oct 20, 2026",
    status: "Open",
    description:
      "Startupbootcamp FinTech APAC supports founders building payments, compliance, and embedded finance products. Teams gain direct access to regulated partners and enterprise channels. The program emphasizes distribution and sustainable economics from day one.",
    eligibility: [
      "Fintech startup with active pilots or enterprise discussions",
      "Regulatory awareness in at least one APAC market",
      "Ability to engage with corporate partners",
    ],
    perks: [
      { title: "Corporate Access", detail: "Banks and fintech platform introductions" },
      { title: "Mentors", detail: "Fintech operators and compliance specialists" },
      { title: "Investment", detail: "Program capital and demo day exposure" },
      { title: "Global Reach", detail: "International alumni network" },
    ],
    featured: false,
    icon: "account_balance",
    stickyColor: "#EDE9FE",
  },
  {
    id: "africa-no-filter-grants",
    name: "No Filter Founder Grants",
    org: "Africa No Filter",
    type: "Grant",
    region: "Africa",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$20,000",
    duration: "3 months",
    location: "Remote",
    deadline: "Closed",
    status: "Closed",
    description:
      "No Filter Founder Grants support narrative-changing media and community ventures across Africa. Teams receive non-dilutive funding for early experimentation and storytelling-driven growth. The initiative prioritizes underrepresented founders creating public value.",
    eligibility: [
      "Africa-based founder or team",
      "Clear social impact mission and audience",
      "Project scope suitable for grant timeline",
    ],
    perks: [
      { title: "Grant", detail: "Non-dilutive support for early execution" },
      { title: "Story Support", detail: "Narrative strategy and amplification" },
      { title: "Community", detail: "Peer cohort and mentor touchpoints" },
      { title: "Visibility", detail: "Showcase across partner channels" },
    ],
    featured: false,
    icon: "campaign",
    stickyColor: "#FCE7F3",
  },
  {
    id: "seedstars-latam-health",
    name: "Seedstars Health LATAM",
    org: "Seedstars",
    type: "Fellowship",
    region: "LATAM",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$35,000",
    duration: "12 weeks",
    location: "Mexico City / Hybrid",
    deadline: "Sep 2, 2026",
    status: "Open",
    description:
      "Seedstars Health LATAM supports startups improving healthcare access and affordability in underserved communities. Fellows receive expert coaching and practical pathways to scale through partnerships. The program combines mission impact with disciplined business execution.",
    eligibility: [
      "Health-focused startup in LATAM",
      "Product with active users or provider pilots",
      "Commitment to hybrid fellowship participation",
    ],
    perks: [
      { title: "Catalytic Funding", detail: "Equity-free stipend for milestone execution" },
      { title: "Mentorship", detail: "Healthcare operators and policy experts" },
      { title: "Pilot Access", detail: "Introductions to regional health partners" },
      { title: "Investor Prep", detail: "Fundraising and financial modeling support" },
    ],
    featured: false,
    icon: "favorite",
    stickyColor: "#FFEDD5",
  },
  {
    id: "on-deck-climate-fellows",
    name: "OD Climate Fellows",
    org: "On Deck",
    type: "Fellowship",
    region: "Global",
    focus: "Climate",
    equity: "Equity-free",
    stipend: "None",
    duration: "10 weeks",
    location: "Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "OD Climate Fellows convenes builders, researchers, and operators advancing decarbonization ventures. The fellowship is network-first, helping founders pressure-test ideas and recruit collaborators. Participants leave with clearer roadmaps and stronger access to specialized talent.",
    eligibility: [
      "Founder or builder working on climate problems",
      "Ability to engage in weekly peer sessions",
      "Commitment to measurable project outcomes",
    ],
    perks: [
      { title: "Network", detail: "Curated climate founder and expert community" },
      { title: "Learning", detail: "Workshops on policy, science, and go-to-market" },
      { title: "Collaboration", detail: "Team and advisor matching" },
      { title: "Visibility", detail: "Demo and storytelling opportunities" },
    ],
    featured: false,
    icon: "co2",
    stickyColor: "#DCFCE7",
  },
  {
    id: "plug-and-play-insurtech",
    name: "InsurTech Batch",
    org: "Plug and Play",
    type: "Accelerator",
    region: "North America",
    focus: "Fintech",
    equity: "Equity-free",
    stipend: "None",
    duration: "14 weeks",
    location: "Sunnyvale / Hybrid",
    deadline: "Nov 3, 2026",
    status: "Open",
    description:
      "Plug and Play connects insurtech startups with carriers and enterprise partners through a structured acceleration cycle. The program focuses on pilot opportunities and commercial traction. Teams also gain introductions to strategic investors active in the sector.",
    eligibility: [
      "Insurtech startup with enterprise-ready product",
      "Ability to run pilots with corporate partners",
      "Team commitment for in-person and virtual sessions",
    ],
    perks: [
      { title: "Pilot Access", detail: "Direct enterprise partnership opportunities" },
      { title: "Mentors", detail: "Insurance and fintech specialists" },
      { title: "Network", detail: "Global innovation platform ecosystem" },
      { title: "Investor Intros", detail: "Access to sector-focused capital" },
    ],
    featured: false,
    icon: "shield",
    stickyColor: "#DBEAFE",
  },


  {
    id: "south-park-commons-fall-2026",
    name: "SPC Founder Fellowship Fall 2026",
    org: "South Park Commons",
    type: "Fellowship",
    region: "North America",
    focus: "Deep Tech",
    equity: "7%",
    stipend: "$400,000",
    duration: "6 months",
    location: "San Francisco / New York / Bangalore",
    deadline: "Aug 2026 (TBA)",
    status: "Open",
    description:
      "South Park Commons partners with founders in the '-1 to 0' pre-idea phase, helping technical builders find the right company to start. Cohorts are deliberately small with one partner per two teams and no fixed demo day. Fellows receive $400k upfront plus $600k guaranteed in their next venture round.",
    eligibility: [
      "Technical founder or domain expert with venture intent",
      "Willingness to ideate and iterate during the program",
      "Full-time availability at an SPC office location",
    ],
    perks: [
      { title: "Investment", detail: "$400k for 7% SAFE + $600k guaranteed next round" },
      { title: "Partner Support", detail: "1:1 partner sessions multiple times per week" },
      { title: "Credits", detail: "Up to $1M in cloud and tool credits (Anthropic, AWS, GCP)" },
      { title: "Community", detail: "Lifetime access to SPC's technical founder network" },
    ],
    featured: true,
    icon: "hub",
    stickyColor: "#FEF9C3",
  },
  {
    id: "ai2-incubator-rolling",
    name: "AI2 Incubator",
    org: "Allen Institute for AI",
    type: "Incubator",
    region: "North America",
    focus: "Deep Tech",
    equity: "Varies",
    stipend: "$600,000",
    duration: "12 months",
    location: "Seattle / In-Person",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "AI2 Incubator backs applied AI startups with up to $600k in capital and $1M in compute credits, alongside hands-on support from AI researchers and operators. Over 90% of incubated companies go on to raise venture funding. The program provides recruiting, design, business development, and go-to-market support under one roof.",
    eligibility: [
      "AI-first startup with a strong technical founder",
      "Clear path from research to real-world product",
      "Ability to work from Seattle during the program",
    ],
    perks: [
      { title: "Capital", detail: "Up to $600k investment" },
      { title: "Compute", detail: "$1M in AI compute credits" },
      { title: "Research Access", detail: "Direct collaboration with AI2 researchers" },
      { title: "BD Support", detail: "Enterprise pilot introductions and partner network" },
    ],
    featured: true,
    icon: "memory",
    stickyColor: "#DBEAFE",
  },
  {
    id: "berkeley-skydeck-batch-23",
    name: "Berkeley SkyDeck Cohort",
    org: "Berkeley SkyDeck",
    type: "Accelerator",
    region: "North America",
    focus: "General",
    equity: "7.5%",
    stipend: "$200,000",
    duration: "6 months",
    location: "Berkeley, CA / In-Person",
    deadline: "Rolling (bi-annual)",
    status: "Rolling",
    description:
      "Berkeley SkyDeck is one of the world's most globally connected university accelerators, drawing on UC Berkeley's network of 600,000+ alumni and 900 advisors. Around 20 startups per cohort receive $200k investment and go through the Berkeley Acceleration Method (BAM) before presenting at a 600+ attendee Demo Day.",
    eligibility: [
      "MVP-stage startup with early traction or angel funding",
      "Industry-agnostic; international founders strongly encouraged",
      "Ability to spend meaningful time in the Bay Area",
    ],
    perks: [
      { title: "Investment", detail: "$200k from Berkeley SkyDeck Fund" },
      { title: "Advisors", detail: "900+ active mentors and industry experts" },
      { title: "Demo Day", detail: "600+ investor and partner audience" },
      { title: "Resources", detail: "$750k+ in legal, financial, and tech credits" },
    ],
    featured: false,
    icon: "school",
    stickyColor: "#EDE9FE",
  },
  {
    id: "third-derivative-d3",
    name: "Third Derivative (D3) Climate Tech",
    org: "RMI + New Energy Nexus",
    type: "Accelerator",
    region: "Global",
    focus: "Climate",
    equity: "Equity-free",
    stipend: "$100,000",
    duration: "18 months",
    location: "Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "Third Derivative is one of the world's largest climate tech accelerators, supporting 286+ portfolio companies across energy, industry, food, and land. The program runs for 18 months virtually and connects startups with a deep network of corporate partners, investors, and policy experts.",
    eligibility: [
      "Climate tech startup with measurable emissions impact",
      "Pre-seed through Series A stage",
      "Technical team with clear path to commercial deployment",
    ],
    perks: [
      { title: "Convertible Note", detail: "Optional $100k investment available" },
      { title: "Corporate Access", detail: "Introductions to 70+ innovation partners" },
      { title: "Investor Network", detail: "Warm intros to climate-focused funds" },
      { title: "Global Community", detail: "286+ portfolio company peer network" },
    ],
    featured: true,
    icon: "energy_savings_leaf",
    stickyColor: "#DCFCE7",
  },
  {
    id: "forum-ventures-b2b-saas",
    name: "Forum Ventures B2B Accelerator",
    org: "Forum Ventures",
    type: "Accelerator",
    region: "North America",
    focus: "General",
    equity: "7.5%",
    stipend: "$100,000",
    duration: "4 months",
    location: "New York / Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "Forum Ventures specializes in early-stage B2B SaaS and fintech, providing laser-focused support on sales, GTM execution, and investor readiness. The program is NYC-based but runs hybrid, and $100k+ in additional partner perks accompanies each investment. Alumni companies have raised over $1B in follow-on funding.",
    eligibility: [
      "Pre-seed B2B SaaS or fintech startup",
      "At least one founder with commercial or technical domain expertise",
      "MVP with initial customer validation",
    ],
    perks: [
      { title: "Investment", detail: "$100k via post-money SAFE" },
      { title: "Perks", detail: "$100k+ in additional tool and service credits" },
      { title: "Sales Coaching", detail: "Hands-on GTM and pipeline support" },
      { title: "Investor Intros", detail: "Access to seed-stage fund network" },
    ],
    featured: false,
    icon: "trending_up",
    stickyColor: "#FEF9C3",
  },
  {
    id: "ai-grant-nat-gross",
    name: "AI Grant",
    org: "Nat Friedman & Daniel Gross",
    type: "Grant",
    region: "Global",
    focus: "Deep Tech",
    equity: "Uncapped SAFE",
    stipend: "$250,000",
    duration: "Self-directed",
    location: "Remote",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "AI Grant backs AI-native product builders with $250k on an uncapped SAFE, plus over $600k in cloud and compute credits. The program is deliberately lightweight — no cohort schedule, no curriculum — giving founders maximum focus time. It is best suited for technical teams who want capital and compute with minimal overhead.",
    eligibility: [
      "Technical team building an AI-native product",
      "Strong founder conviction and prior domain expertise",
      "Self-directed builders comfortable without structured programming",
    ],
    perks: [
      { title: "Capital", detail: "$250k uncapped SAFE" },
      { title: "Credits", detail: "$600k+ in AI cloud and API credits" },
      { title: "Network", detail: "Access to Nat Friedman and Daniel Gross network" },
      { title: "Autonomy", detail: "No mandatory sessions or curriculum" },
    ],
    featured: true,
    icon: "smart_toy",
    stickyColor: "#EDE9FE",
  },
  {
    id: "ewor-fellowship-europe",
    name: "EWOR Fellowship",
    org: "EWOR",
    type: "Fellowship",
    region: "Europe",
    focus: "General",
    equity: "0–2%",
    stipend: "€500,000",
    duration: "Ongoing / Virtual-first",
    location: "Remote / Europe",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "EWOR is a founder fellowship structured around deep operator access rather than a traditional cohort sprint. With an acceptance rate near 0.1%, it targets ambitious European founders aiming for venture-scale outcomes. Select fellows receive up to €500k in funding and regular sparring with unicorn founders.",
    eligibility: [
      "Highly ambitious founder with a clear venture thesis",
      "Willingness to engage in intensive operator-led coaching",
      "Europe-based or European-market focused",
    ],
    perks: [
      { title: "Investment", detail: "Up to €500k for a 0–2% education fee" },
      { title: "Operator Access", detail: "Sparring with unicorn founders and builders" },
      { title: "Bespoke Support", detail: "Personalized rather than curriculum-driven" },
      { title: "Network", detail: "Elite European founder and investor community" },
    ],
    featured: false,
    icon: "star",
    stickyColor: "#FCE7F3",
  },
  {
    id: "greentown-labs-climatetech",
    name: "Greentown Labs Incubator",
    org: "Greentown Labs",
    type: "Incubator",
    region: "North America",
    focus: "Climate",
    equity: "Equity-free",
    stipend: "None",
    duration: "Ongoing",
    location: "Boston / Houston",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "Greentown Labs is the largest climatetech incubator in North America with facilities in Boston and Houston. Member startups access fully equipped prototyping labs, maker spaces, and a dense community of climate operators, investors, and corporate partners. The model is membership-based with no equity taken.",
    eligibility: [
      "Climate or clean energy startup at any stage",
      "Benefit from physical lab and prototyping resources",
      "Able to maintain a Boston or Houston presence",
    ],
    perks: [
      { title: "Lab Access", detail: "State-of-the-art hardware and testing facilities" },
      { title: "Community", detail: "200+ member startups in two locations" },
      { title: "Corporate Partners", detail: "Direct access to energy sector incumbents" },
      { title: "No Equity", detail: "Membership fee model, zero dilution" },
    ],
    featured: false,
    icon: "factory",
    stickyColor: "#DCFCE7",
  },
  {
    id: "station-f-paris",
    name: "Station F Founders Program",
    org: "Station F",
    type: "Incubator",
    region: "Europe",
    focus: "General",
    equity: "Equity-free",
    stipend: "None",
    duration: "Ongoing",
    location: "Paris / In-Person",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "Station F is the world's largest startup campus, hosting over 1,000 startups alongside VCs, corporate innovation labs, and public programs in a single Paris campus. Founders benefit from constant proximity to capital and partnerships rather than structured cohort support. Best for self-directed teams scaling in Europe with international investor exposure.",
    eligibility: [
      "Incorporated startup with at least one full-time founder",
      "Product beyond pure ideation stage",
      "Ability to be physically present in Paris",
    ],
    perks: [
      { title: "Workspace", detail: "Desk and office space in a 34,000 sqm campus" },
      { title: "Ecosystem", detail: "50+ partner programs and VC firms on-site" },
      { title: "Events", detail: "Weekly investor and founder networking events" },
      { title: "Visa Support", detail: "French Tech Visa facilitation for international founders" },
    ],
    featured: false,
    icon: "location_city",
    stickyColor: "#FFEDD5",
  },
  {
    id: "startmate-australia-2026",
    name: "Startmate Accelerator",
    org: "Startmate",
    type: "Accelerator",
    region: "Asia",
    focus: "General",
    equity: "Varies",
    stipend: "AUD $120,000",
    duration: "12 weeks",
    location: "Sydney / Melbourne",
    deadline: "Nov 2026 (TBA)",
    status: "Open",
    description:
      "Startmate is Australia and New Zealand's most prominent accelerator, running a 12-week intensive program for early-stage startups. Teams receive AUD $120k at a $1.5M post-money valuation and access to a deeply engaged operator and investor community. The program is known for its unusually high mentor-to-founder ratio.",
    eligibility: [
      "Early-stage startup, ideally Australia or NZ based",
      "Working product with initial customer evidence",
      "Full-time commitment from at least one founder",
    ],
    perks: [
      { title: "Investment", detail: "AUD $120k at $1.5M post-money valuation" },
      { title: "Mentors", detail: "High mentor-to-founder ratio from top operators" },
      { title: "Network", detail: "Access to AU/NZ and global investor base" },
      { title: "Alumni", detail: "Strong peer community across cohorts" },
    ],
    featured: false,
    icon: "flight_takeoff",
    stickyColor: "#FEF9C3",
  },
  {
    id: "mozilla-democracy-ai-incubator",
    name: "Mozilla Democracy & AI Incubator",
    org: "Mozilla Foundation",
    type: "Grant",
    region: "Global",
    focus: "Social Impact",
    equity: "Equity-free",
    stipend: "$300,000",
    duration: "12 months",
    location: "Remote",
    deadline: "Rolling",
    status: "Open",
    description:
      "Mozilla's Democracy & AI Incubator funds global innovators building products that strengthen democratic institutions, counter disinformation, and improve civic technology. Grants go up to $300k with no equity taken. Teams also receive mentorship from Mozilla's network of internet health advocates and technical experts.",
    eligibility: [
      "Organization or startup focused on AI and democratic governance",
      "Clear plan for civic impact and responsible AI deployment",
      "Global founders welcome; English proficiency required",
    ],
    perks: [
      { title: "Grant", detail: "Up to $300k non-dilutive funding" },
      { title: "Network", detail: "Mozilla foundation and partner ecosystem" },
      { title: "Mentorship", detail: "Experts in AI policy and civic tech" },
      { title: "Visibility", detail: "Platform exposure through Mozilla's channels" },
    ],
    featured: false,
    icon: "gavel",
    stickyColor: "#EDE9FE",
  },
  {
    id: "on-deck-founder-fellowship-odf",
    name: "On Deck Founder Fellowship",
    org: "On Deck",
    type: "Fellowship",
    region: "Global",
    focus: "General",
    equity: "Equity-free",
    stipend: "None",
    duration: "10 weeks + year-long community",
    location: "Remote / SF Sprint Week",
    deadline: "Rolling",
    status: "Rolling",
    description:
      "On Deck Founder Fellowship (ODF) is a network-first program for founders at any stage. The format includes a one-week in-person sprint in San Francisco followed by a year-long community membership. It is especially valuable for founders looking for high-quality co-founder matches, advisors, and investor warm intros.",
    eligibility: [
      "Founder or aspiring founder at any stage",
      "Strong commitment to peer engagement",
      "Ability to attend the SF sprint week",
    ],
    perks: [
      { title: "Community", detail: "Year-long access to curated founder network" },
      { title: "Co-founder Matching", detail: "Structured introductions and team formation" },
      { title: "Investor Access", detail: "Warm intros to seed-stage investors" },
      { title: "Pay-what-you-can", detail: "~$1k suggested, no equity taken" },
    ],
    featured: false,
    icon: "diversity_3",
    stickyColor: "#FCE7F3",
  },
  {
    id: "techstars-new-york-2026",
    name: "Techstars New York",
    org: "Techstars",
    type: "Accelerator",
    region: "North America",
    focus: "General",
    equity: "6%",
    stipend: "$120,000",
    duration: "13 weeks",
    location: "New York City / In-Person",
    deadline: "Jun 10, 2026",
    status: "Open",
    description:
      "Techstars New York is one of the flagship city programs in the Techstars network, offering intensive mentorship, a $220k combined investment package, and access to NYC's dense startup ecosystem. The program runs on a fixed cohort model with a prominent Demo Day and lifetime alumni membership.",
    eligibility: [
      "Pre-seed or seed-stage startup in any vertical",
      "Two or more committed founders preferred",
      "Willingness to work from NYC during the program",
    ],
    perks: [
      { title: "Investment", detail: "$220k combined equity and MFN SAFE" },
      { title: "Perks", detail: "$2M+ in partner tool credits" },
      { title: "Mentor Network", detail: "Curated NYC operator and investor mentors" },
      { title: "Demo Day", detail: "High-profile investor and media event" },
    ],
    featured: false,
    icon: "apartment",
    stickyColor: "#DBEAFE",
  },
];